name: GitHub Actions Demo
on: [push, workflow_dispatch]
jobs:
  exe_numpy:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
            python-version: 3.9.7
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
          target: x86_64-pc-windows-msvc
      - run: git clone https://github.com/franzhaas/numpy.git
      - run: pip install wheel
      - run: pip wheel -w . .
      - run: cargo install --git https://github.com/franzhaas/PyOxidizer.git --branch enable_multiphase_initialisation_using_incref pyoxidizer
      - run: cargo install --git https://github.com/franzhaas/PyOxidizer.git --branch enable_multiphase_initialisation_using_incref pyoxy
      - run: cargo install --git https://github.com/franzhaas/PyOxidizer.git --branch enable_multiphase_initialisation_using_incref release
      - run: pyoxidizer build install
      - run: numpy_sinlge_file_executable\build\x86_64-pc-windows-msvc\debug\install\numpy_pytest.exe -c "import numpy; numpy.test(extra_argv=['--assert=plain'])"
      - name: Archive exe
        uses: actions/upload-artifact@v2
        with:
          name: archive
          path: build\x86_64-pc-windows-msvc\debug\*
