name: GitHub Actions Demo
on: [push, workflow_dispatch]
jobs:
  exe_numpy:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
            python-version: 3.9.9
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
          target: x86_64-pc-windows-msvc
      - run: cargo install --git https://github.com/indygreg/PyOxidizer.git pyoxidizer
      - run: cargo install --git https://github.com/indygreg/PyOxidizer.git pyoxy
      - run: cargo install --git https://github.com/indygreg/PyOxidizer.git release
      - run: pyoxidizer build installer
      - run: pyoxidizer build exe
      - name: Archive exe
        uses: actions/upload-artifact@v2
        with:
           name: archive
           path: build\*

