name: GitHub Actions Demo
on: [push, workflow_dispatch]
jobs:
  exe_numpy:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
            python-version: 3.9.9
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
          target: x86_64-pc-windows-msvc
      - run: pip install wheel
      - run: pip wheel -w . .
      - run: pip wheel -w . git+https://github.com/franzhaas/numpy.git#egg=numpy
      - run: dir
      - run: cargo install --git https://github.com/franzhaas/PyOxidizer.git --branch franzhaas-borrowed_ptr pyoxidizer
      - run: cargo install --git https://github.com/franzhaas/PyOxidizer.git --branch franzhaas-borrowed_ptr pyoxy
      - run: cargo install --git https://github.com/franzhaas/PyOxidizer.git --branch franzhaas-borrowed_ptr release
      - run: pyoxidizer build exe
      - run: Start-Process .\build\x86_64-pc-windows-msvc\debug\install\numpy_pytest.exe -ArgumentList "-c `"import numpy; numpy.test(extra_argv=['--assert=plain'])`""
      - name: Archive exe
        uses: actions/upload-artifact@v2
        with:
          name: archive
          path: build\x86_64-pc-windows-msvc\debug\*
